"""Fish completion generation for tyro using embedded Python logic."""

from __future__ import annotations

from ... import _parsers
from ._base import CompletionGenerator
from ._python_completer import get_embedded_code
from ._spec import build_completion_spec


class TyroFishCompletionGenerator(CompletionGenerator):
    """Generates Fish completion scripts with embedded Python logic."""

    def generate(
        self,
        parser_spec: _parsers.ParserSpecification,
        prog: str,
        root_prefix: str,
    ) -> str:
        """Generate a Fish completion script.

        Args:
            parser_spec: Parser specification to generate completion for.
            prog: Program name.
            root_prefix: Prefix for completion function names.

        Returns:
            Fish completion script as a string.
        """
        # Build completion spec.
        spec = build_completion_spec(parser_spec, prog)
        spec_repr = repr(spec)

        # Get embedded Python code.
        python_code = get_embedded_code()

        # The spec and Python code are embedded inside a fish double-quoted
        # string (`set -l pycode "..."`). Inside fish double quotes, only `\`,
        # `"`, and `$` are special, so we must escape exactly those (and only
        # those) to avoid corrupting the script. A default value or help string
        # containing e.g. a quote or `$` would otherwise prematurely close the
        # string or trigger variable expansion. Backslash must be escaped first.
        def _fish_escape_dq(text: str) -> str:
            return text.replace("\\", "\\\\").replace('"', r"\"").replace("$", r"\$")

        pycode_body = _fish_escape_dq(
            f"# Hardcoded completion spec.\nCOMPLETION_SPEC = {spec_repr}\n{python_code}"
        )

        # Generate the fish completion script.
        script = f"""# AUTOMATICALLY GENERATED by tyro

# Main completion function.

function _{root_prefix}
    if command -sq python3
        set python_cmd python3
    else if command -sq python
        set python_cmd python
    else
        return
    end

    # Collect commandline tokens for completion.
    #
    # Newer fish versions support `commandline -xpc`, which returns tokens
    # with proper cursor-aware parsing and expansion semantics.
    #
    # Older fish versions do not support `-x`, and only provide `-opc`.
    # Although `-o` is deprecated in newer fish, it is still required as
    # a fallback for compatibility.
    #
    # Therefore:
    #   - Prefer `-xpc` when available.
    #   - Fall back to `-opc` on older fish versions.

    set -l words
    if commandline -x >/dev/null 2>&1
        set words (commandline -xpc)
    else
        set words (commandline -opc)
    end

    set -l current (count $words)
    set -l pycode "{pycode_body}"
    set -l results ($python_cmd -c "$pycode" $words $current)
    if test "$results" = __TYRO_COMPLETE_FILES__
        __fish_complete_path (commandline -ct)
    else
        for line in $results
            printf "%s\\n" $line
        end
    end
end

# Register completion for the full program name.
complete --no-files --command {prog} --arguments "(_{root_prefix})"

# Also register for basename to handle ./script invocations.
# Guard against re-registering the same command name (when prog is already a
# bare name, basename == prog and ./basename collides with prog), which would
# otherwise produce duplicate completion candidates.
set _prog_basename (basename {prog})
if test "$_prog_basename" != {prog}
    complete --no-files --command $_prog_basename --arguments "(_{root_prefix})"
end
if test "./$_prog_basename" != {prog}
    complete --no-files --command "./$_prog_basename" --arguments "(_{root_prefix})"
end
"""
        return script
